# Your preferred name/username (to be displayed in the blog header)
name = "Stelleron"

# Your About and Projects page location
about = "posts/special/about.md"
projects = "posts/special/projects.md"

[footer]
# Your GitHub profile link(uncomment to add)
github = "https://github.com/stelleron"